### ISSUE TITLE
Incorrect Monitor Behaviour in LRZ2 

### ISSUE THREAD

**Issue by TrackerTD** [Rubberduckycooly/Sonic-Mania-Decompilation#91] opened 2022-08-23 19:59 UTC
Extremely minor, but if the monitor on the conveyor in LRZ2 is broken before it reaches the Lava, it just slides across the surface. It's supposed to sink (which it does correctly, if it's not broken). 

Decomp:
![ManiaDecompBrokeMonitorSlide](https://user-images.githubusercontent.com/71041044/186254443-16f9beae-3190-4a2d-8668-91919081c6ed.gif)

Steam release:
![ManiaVanillaBrokeMonitorSink](https://user-images.githubusercontent.com/71041044/186254472-ec8aecae-b0d8-41be-b353-5e5a026d74c0.gif)

**Comment by Rubberduckycooly** [comment] 2022-08-24 06:09
this one's *really* weird, I can't reproduce it and looking at mania's logic the "intended" behaviour is to stay on the lava I think? Itemboxes should usually sink, but broken itemboxes always do tile collision checks, it's the same reason why itemboxes don't follow the lift from TMZ1 boss to TMZ2 but broken itemboxes do.

Please let me know if there's any more specifics I should know on how to replicate or if you can replicate it on steam again

**Comment by TrackerTD** [comment] 2022-08-24 14:33
Tested both again, with no mods loaded on anything. Works just as in the gifs. Hit the monitor before it lands in the lava, and it sinks in vanilla, slides on decomp. I'm using v5U, 64-bit dx11 build.

**Comment by Rubberduckycooly** [comment] 2022-08-25 07:36
fixed in 2669dd85e3c228d253cf1c6034c0d07bedca6db1

**Closed by Rubberduckycooly** 2022-08-25 07:36 UTC
Labels: incorrect behavior
