### ISSUE TITLE
Sonic Mania 1.00/1.03 (Pre-Plus): Main Menu bug.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-Mania-Decompilation#74] opened 2022-08-19 16:39 UTC
it just doesn't exist

it's gone.

![image](https://user-images.githubusercontent.com/24783625/185666500-8d6e4846-acf2-4e10-beaa-5c0346571b3c.png)

im deadass it literally just doesn't work LOL

**Comment by breakthetargets** [comment] 2022-08-19 17:40
It does exist, it's just very, very, very, very, very dim

**Comment by Rubberduckycooly** [comment] 2022-08-21 11:49
Can't reproduce, is there anymore info I should know about the issue?

**Comment by LittlePlanetCD** [comment] 2022-08-21 17:22
all I know is that I used a 1.00 Mania data file, and compiled Game Version with VER_100 in the Game.h file for the Mania decomp.

i also compiled RSDKv5 but as rev 1 instead of 2 in the SLN.

The rest of the game just works, but it does not want to get through to the menu.

I can actually "Interact" with the main menu, but it only makes the navigation beep noise.

There's also no autosave prompt. it just never happens.

There might be a bit more but I don't remember if there is.

**Comment by LittlePlanetCD** [comment] 2022-08-21 17:26
this also affects a normal 1.03 compile for "Pre-Plus" too, which is really strange.

I'm compiling by myself, using Visual Studio and building release x64.

**Comment by Rubberduckycooly** [comment] 2022-08-23 04:44
fixed in 9b535f85cd5ecdd36a5d143bf64e7dbd64257ef7

**Closed by Rubberduckycooly** 2022-08-23 04:44 UTC
