### ISSUE TITLE
Press Garden Zone act 2 boss bug

### ISSUE THREAD

**Issue by cgamebit** [Rubberduckycooly/Sonic-Mania-Decompilation#81] opened 2022-08-20 00:18 UTC
I'm playing on a Motorola Moto G9 play, the standard Steam Sonic Mania. When I get to the boss he is behind a pillar and that makes it impossible to face him. I can't get to his side and the boss keeps going out of view of the screen and always behind this pillar. I tried a few times to exit the game but the bug persists.

**Comment by cgamebit** [comment] 2022-08-20 00:33
![Screenshot_20220819-213238](https://user-images.githubusercontent.com/106029761/185722368-64e5b14f-7684-492f-a8bb-2db260b8fdce.png)

**Comment by ActualMandM** [comment] 2022-08-20 05:16
From experimentation, this looks to be caused by a wider aspect ratio in addition to the player quickly going to the boss area. A workaround is to slowly walk to the boss area.

https://user-images.githubusercontent.com/15317421/185730074-d15bb815-2cf8-487d-8f07-cd93d4ec1818.mp4

**Comment by cgamebit** [comment] 2022-08-21 16:03
I managed to beat the boss but I had to stay in the left corner as much as possible. If I walked a little forward, the bug occurs and it is necessary to restart the level. Tried taking out ultrawide and vsync mode and it didn't work.
![Screenshot_20220821-125605](https://user-images.githubusercontent.com/106029761/185800118-52bdea36-c0af-4abb-a092-d8f7cbfd99fc.png)

**Comment by MGRich** [comment] 2022-08-22 03:40
This is an Ultra-wide Mania mod bug. It's supposed to actually fix this entirely but something must've gone wrong or changed later in development. I'll get to fixing it soon, and will circle back here with the updated commit. This will be fixed pre-packaged with version 1.1 of the decompilation as well.

**Closed by MGRich** 2022-08-22 03:40 UTC

**Comment by ActualMandM** [comment] 2022-08-29 05:22
fixed in Ultrawide Mania with https://github.com/Rubberduckycooly/RSDKv5-Example-Mods/commit/b2b4fd66f013ff17d14a57c447ef4f825ee04017
