### ISSUE TITLE
Green Hill S-Tube Flips Rolling Sprite Orientation

### ISSUE THREAD

**Issue by TrackerTD** [Rubberduckycooly/Sonic-Mania-Decompilation#48] opened 2022-08-17 19:39 UTC
When rolling through a tube such as the one as the end of Green Hill Zone Act 1, Sonic's sprite seems to stick to one side of the tube and the rolling sprite is flipped vertically. From my testing this is inaccurate to Mania.
![maniaDecompS-TubeFlipGit](https://user-images.githubusercontent.com/71041044/185227827-b29a32f5-a4a9-462c-8838-7821678709e8.gif)

**Comment by Rubberduckycooly** [comment] 2022-08-20 04:12
Unable to reproduce this one. Are there any more specific steps that I should follow? The ForceSpin object doesn't change sonic's direction at all.

**Comment by TrackerTD** [comment] 2022-08-20 13:38
Yeah now I can't reproduce it either, odd. Maybe it was a mod glitch I didn't notice!

**Comment by Rubberduckycooly** [comment] 2022-08-21 11:27
I'll close this for now, feel free to reopen & tag me or make another issue if you can find a way to preproduce it (at least somewhat) reliably!

**Closed by Rubberduckycooly** 2022-08-21 11:27 UTC
