### ISSUE TITLE
[Plus] Mods with the bead worm in a different level don't work well

### ISSUE THREAD

**Issue by Insane-Freddy** [Rubberduckycooly/Sonic-Mania-Decompilation#181] opened 2023-02-10 13:53 UTC
So, a good example would be hilltop zone from the misfits pack, upon beating the bead worm, if freezes then crashes.

**Comment by LittlePlanetCD** [comment] 2023-02-10 19:26
not a valid issue, you're using a mod that's not fully finished for decomp.

please don't make issues for mods that are broken on the Mania decomp page.

**Comment by Insane-Freddy** [comment] 2023-02-14 14:02
It's not the mods that causes this tho

**Comment by Insane-Freddy** [comment] 2023-02-14 14:06
It's like this for multiple mods tho, I think its some different coding from tye decomp version that makes multiple mods unplayable

**Comment by stxticOVFL** [comment] 2023-02-16 03:33
The mods that are affected normally use something called unlock codes for the Steam release. These unlock codes are essentially maps to memory, and their behavior cannot be replicated at all in the decompilation. This is not a bug of the decomp; this is something that would normally be resolved by the Steam mod loader.

**Closed by stxticOVFL** 2023-02-16 03:33 UTC
